package com.example.APIPONTOJOIN.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Entity
@Table(name = "ADRI_PESSOA_JOIN")
public class pessoaModel {

    //  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    //  nome VARCHAR2(50) NOT NULL,
    //  idade NUMBER(3) NOT NULL,
    //  sexo CHAR(1) NOT NULL,
    //  PRIMARY KEY (id)
    //);

    @Id
    @Column(name = "ID")
    private int id;

    @Column(name = "NOME")
    private String nome;

    @Column(name = "IDADE")
    private int idade;

    @Column(name = "SEXO")
    private char sexo;

}
